distr: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: HWxFBmOu+5LXL/xDfECrAXkTLH2cgr/ZtmrDXkIwyoA9wBiu23uVjZtrMgpION6llKkGaHUekGrNpNMvPfgrnDiaeJpPmlyZVg3TNCMx1UfY/Gyh5Pody32vVdM+vMxChFKmsJ1AVuNF4VQ9FWje7pln+s7iGCatkoPKFbFOVdWII6uYUf8D7kFGIoDCVbNliHbl3MYHA18Pi/auYi+9iegeybVIkSdhNEFc4lrzOVbcXREsXDvx58WWKPjAkgdAr6X0RjeccvfHCcJhmQXnxZO3WXvgYipwe01J8lTF9oIutynHFpzedYeds4RwpWpFYeTT0w/TdBp23duzrZ7Vnu466g/zshcNliH6NK0Ue3WGOlapsar4aBZRECFPNzO3/+UgGePwiAC7k9rfQpjIoWelveKQrPMDKV8iNbfC1mZ2+6H9422HyylmoFfIPTfjO2jv1u5SJBwz4k+l/T7/SW3z+8ZQPZApyIfYVaY0FyiHsjdveCNw4Vun2pmlmQRlMHUrka2CmqLCqlpVghP3d+5nPYUjtfb6Off5i1MoxoVWBKkb1pbawGJqyVjGm8qZl0mDAEjf2PMfXCqCESn8gw5Zdz9eH2dawT7vh32SqbebEIAJiyLfobnRC0r3Yqa5LWfklYmHpMpw2C/cNSgWN19Xx/ljonKxk+9TvMdu0uo=
