---
- name: install ruby
  hosts: all
  become: yes
  tags: install-ruby
  tasks:
  - name: repair apt
    raw: sudo dpkg --configure -a
  - name: install packages
    apt: 
      name: "{{ item }}"
      state: present
    loop:
      - ruby-full
      - ruby-bundler
      - build-essential
