---
- name: install ruby
  hosts: all
  become: yes
  tags: install-ruby
  tasks:
  - name: install packages
    apt: 
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - ruby-full
      - ruby-bundler
      - build-essential
